"""Markdown renderer for PR/Issue reports."""

from rhc.renderers.base import BaseRenderer
from rhc.types import Report, Severity

# Severity to emoji for markdown
SEVERITY_BADGES = {
    Severity.CRITICAL: "🔴 Critical",
    Severity.HIGH: "🟠 High",
    Severity.MEDIUM: "🟡 Medium",
    Severity.LOW: "🔵 Low",
    Severity.INFO: "⚪ Info",
}


class MarkdownRenderer(BaseRenderer):
    """Markdown renderer for PR/Issue integration."""

    def render(self, report: Report) -> str:
        """Render report as Markdown."""
        lines: list[str] = []

        # Header
        lines.append("# Repo Health Check Report")
        lines.append("")

        # Score badge
        grade = report.summary.grade
        score = report.summary.total_score
        lines.append(f"**Score: {score}/100** | **Grade: {grade}**")
        lines.append("")

        # Quick summary
        lines.append("## Summary")
        lines.append("")

        counts = report.summary.counts_by_severity
        summary_parts = []
        for severity in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
            count = counts.get(severity.value, 0)
            if count > 0:
                summary_parts.append(f"{SEVERITY_BADGES[severity]}: {count}")

        if summary_parts:
            lines.append(" | ".join(summary_parts))
        else:
            lines.append("✅ No issues found!")
        lines.append("")

        # Findings table
        if report.findings:
            lines.append("## Findings")
            lines.append("")
            lines.append("| Severity | Check | Issue | Impact |")
            lines.append("|----------|-------|-------|--------|")

            for finding in report.findings:
                sev = SEVERITY_BADGES.get(finding.severity, finding.severity.value)
                lines.append(
                    f"| {sev} | `{finding.id}` | {finding.title} | {finding.score_impact} |"
                )

            lines.append("")

        # Recommendations
        recs = [f for f in report.findings if f.recommendation]
        if recs:
            lines.append("## Recommendations")
            lines.append("")
            for finding in recs[:5]:  # Top 5 recommendations
                lines.append(f"- **{finding.id}**: {finding.recommendation}")
            lines.append("")

        # Metrics
        lines.append("## Repository Info")
        lines.append("")

        if report.metrics.languages_detected:
            lines.append(f"- **Languages**: {', '.join(report.metrics.languages_detected)}")

        if report.metrics.ci_providers_found:
            lines.append(f"- **CI/CD**: {', '.join(report.metrics.ci_providers_found)}")

        if report.metrics.package_managers_found:
            lines.append(f"- **Package Managers**: {', '.join(report.metrics.package_managers_found)}")

        lines.append(f"- **Files scanned**: {report.metrics.files_count}")
        lines.append("")

        # Footer
        lines.append("---")
        git_info = ""
        if report.repo.is_git_repo and report.repo.branch:
            git_info = f" | `{report.repo.branch}`"
            if report.repo.head_sha:
                git_info += f"@`{report.repo.head_sha}`"

        lines.append(
            f"*Generated by rhc v{report.meta.tool_version} in {report.meta.duration_ms}ms{git_info}*"
        )
        lines.append("")

        return "\n".join(lines)
